#!/bin/bash
# Instagram Image Downloader Helper Script
# This script helps download images from Instagram

echo "=========================================="
echo "Andrei Deiu Image Downloader"
echo "=========================================="
echo ""
echo "Since Instagram requires authentication, here are your options:"
echo ""
echo "OPTION 1: Use Online Instagram Downloader"
echo "1. Go to: https://downloadgram.org/"
echo "2. Paste Instagram post URL: https://www.instagram.com/andreideiu_/"
echo "3. Download images"
echo "4. Save as: andrei-1.jpg, andrei-2.jpg, etc."
echo "5. Copy to: assets/images/ folder"
echo ""
echo "OPTION 2: Use Python instagram-scraper"
echo "Run: pip install instaloader"
echo "Then: instaloader andreideiu_ --no-videos --no-captions"
echo ""
echo "OPTION 3: Manual Download"
echo "1. Visit: https://www.instagram.com/andreideiu_/"
echo "2. Right-click each image → Save As"
echo "3. Rename to: andrei-1.jpg through andrei-50.jpg"
echo "4. Copy to: assets/images/ folder"
echo ""
echo "After downloading, run:"
echo "  git add assets/images/"
echo "  git commit -m 'Add Andrei Deiu images'"
echo "  git push origin main"
echo ""
